// Copyright Epic Games, Inc. All Rights Reserved.
// Code generated by generator/generate.py. DO NOT EDIT.

package main

const (
	loreVersion         = "v0.8.3"
	loreRevision        = ""
	loreSiblingRevision = ""
	loreBranch          = ""
	loreSiblingBranch   = ""
	loreName            = ""
	loreReleaseBaseURL  = "https://github.com/EpicGames/lore/releases/download"
	// How the runtime fetcher retrieves the library, baked from the build:
	//   loreArtifactFormat: "direct" (download a raw .so/.dll/.dylib) or
	//     "archive" (download a .tar.gz/.zip bundle and extract the lib).
	//   loreArtifactNaming: "short" (liblore-<tag>-linux-x86_64.so, lore-<tag>.dll)
	//     or "triple" (rust target triples, e.g. -x86_64-unknown-linux-gnu).
	loreArtifactFormat = "archive"
	loreArtifactNaming = "triple"
)
